## NUMPY 

Numpy > List built-in library <br>
Numpy arrays are homogeneous, meaning all elements must be the same type allowing efficient computation <br>
Vectorized operations in NumPy can be 10 to 100 times faster than equivalent Python loops.

In [27]:
import numpy as np

In [31]:
np.random.rand(2,3)

array([[0.76374124, 0.72696338, 0.5685538 ],
       [0.10007863, 0.95433709, 0.8877268 ]])

In [50]:
np.random.randint(15,16,(2,4)) # borne supérieur exclu

array([[15, 15, 15, 15],
       [15, 15, 15, 15]])

In [48]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [49]:
np.array([[1,2],[5,6]])

array([[1, 2],
       [5, 6]])

In [60]:
a0 = np.zeros((3, 3))
a1  = np.ones((2, 6)) 
ar  = np.arange(0, 11, 2) # start end step

print(a0)
print(a1)
print(ar)
print(ar[-1])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[ 0  2  4  6  8 10]
10


In [65]:
a = np.array([10, 20, 30, 40, 50, 60])
idx = np.arange(0,6,2)
print(a[idx])
cond = a> 30
print(a[cond])

[10 30 50]
[40 50 60]


In [66]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])


print(x + y)    # add
print(x - y)    # subtract
print(x * y)    # multiply
print(x / y)    # divide

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## String manipulation 

In [81]:
txt = "Hello World"[:-2]
print(txt) 
txt = "Hello World"[::-2] # prends un caractère sur 2 en partant de la fin 
print(txt)
txt = "Hello World"[::-1]
print(txt) 
import re 
txt = "Hello World"
txt = re.sub("[aeiou]", "", txt)
print(txt)

Hello Wor
drWolH
dlroW olleH
Hll Wrld
